#!/bin/bash
# Quick commands for Phase 1 testing

echo "=================================================="
echo "PHASE 1 MULTI-MODEL TEST - QUICK REFERENCE"
echo "=================================================="
echo ""
echo "📋 JOB IDs:"
echo "  6552895 - orthrus_tuned_cadets_e3 (Phase 1a)"
echo "  6552896 - kairos_phase1_cadets_e3"
echo "  6552897 - magic_phase1_cadets_e3"
echo "  6552898 - magic_adaptive_cadets_e3"
echo ""
echo "=================================================="
echo ""
echo "🔍 MONITORING COMMANDS:"
echo ""
echo "1. Watch all 4 jobs (auto-refresh every 30s):"
echo "   ./scripts/monitor_phase1_jobs.sh"
echo ""
echo "2. Check queue status:"
echo "   squeue -u dunguyen -j 6552895,6552896,6552897,6552898"
echo ""
echo "3. Tail specific job log (replace JOB_ID):"
echo "   tail -f /fred/oz411/dunguyen/slurm-logs/orthrus_tuned_cadets_e3_milan_gpu_6552895.out"
echo "   tail -f /fred/oz411/dunguyen/slurm-logs/kairos_phase1_cadets_e3_milan_gpu_6552896.out"
echo "   tail -f /fred/oz411/dunguyen/slurm-logs/magic_phase1_cadets_e3_milan_gpu_6552897.out"
echo "   tail -f /fred/oz411/dunguyen/slurm-logs/magic_adaptive_cadets_e3_milan_gpu_6552898.out"
echo ""
echo "4. Check last 50 lines of all logs:"
echo "   tail -50 /fred/oz411/dunguyen/slurm-logs/*_{6552895,6552896,6552897,6552898}.out"
echo ""
echo "5. Search for errors in logs:"
echo "   grep -i 'error\|failed\|traceback' /fred/oz411/dunguyen/slurm-logs/*_{6552895,6552896,6552897,6552898}.out"
echo ""
echo "6. Search for success indicators:"
echo "   grep 'Job completed successfully\|TP:\|FP:' /fred/oz411/dunguyen/slurm-logs/*_{6552895,6552896,6552897,6552898}.out"
echo ""
echo "=================================================="
echo ""
echo "✅ SUCCESS CRITERIA:"
echo ""
echo "Orthrus (6552895):"
echo "  - TP ≥ 1 (target: 8-12)"
echo "  - FP ≈ 0"
echo "  - Log shows: 'max_val_node_score' and 'K-means k=2'"
echo ""
echo "Kairos (6552896):"
echo "  - ≥1 anomalous queue detected"
echo "  - Log shows: 'Queue threshold β=X.XX from validation'"
echo ""
echo "Magic Baseline (6552897):"
echo "  - TP > 50 (target: ~63)"
echo "  - High FP (expected ~79K)"
echo "  - Log shows: 'Validation sweep: selected θ='"
echo ""
echo "Magic Adaptive (6552898):"
echo "  - TP ≈ baseline (target: ~63)"
echo "  - FP < baseline × 0.7 (target: 500-2500)"
echo "  - Log shows: 'Collected N FPs for feedback'"
echo ""
echo "=================================================="
echo ""
echo "⚠️  TROUBLESHOOTING:"
echo ""
echo "If job fails, check:"
echo "  1. Error log: tail -100 /fred/oz411/dunguyen/slurm-logs/*_JOB_ID.err"
echo "  2. Output log: tail -100 /fred/oz411/dunguyen/slurm-logs/*_JOB_ID.out"
echo "  3. Import errors: grep 'ImportError\|ModuleNotFoundError' in logs"
echo "  4. Config errors: grep 'KeyError\|AttributeError' in logs"
echo ""
echo "=================================================="
echo ""
echo "📊 EXPECTED RUNTIME:"
echo "  - Orthrus: 30-60 min (GPU)"
echo "  - Kairos: 30-60 min (GPU)"
echo "  - Magic Baseline: 30-60 min (GPU)"
echo "  - Magic Adaptive: 45-90 min (GPU, longer due to adaptation)"
echo ""
echo "=================================================="
